apiVersion: 1

datasources:
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "sensor-data-*"
    jsonData:
      timeField: "@timestamp"
      esVersion: "8.0.0"
      interval: Daily
      logMessageField: message
      logLevelField: level
    editable: true
